// vue/src/components/list-repositories.vue
<template>
  <ul class="list-repositories">
    <li v-for="repository in repositoriesInternal" :key="repository.full_name">
      <router-link :to="`/repositorios/${repository.full_name}`">
        <bar-info
          :title="repository.full_name"
          :description="repository.description"
          :avatar="repository.owner.avatar_url"
          :alt="repository.owner.login"
        />
      </router-link>
    </li>
  </ul>
</template>

<script>
import BarInfo from "@/components/bar-info.vue";
export default {
  name: "ListRepositories",
  components: {
    BarInfo,
  },
  props: {
    repositories: {
      type: Array,
      require: true,
    },
  },
  data() {
    return {
      repositoriesInternal: [],
    };
  },
  watch: {
    repositories(newValue) {
      return (this.repositoriesInternal = newValue);
    },
  },
  mounted() {
    this.repositoriesInternal = this.repositories;
  },
};
</script>

<style lang="scss" scoped>
.list-repositories {
  margin-top: 80px;

  li {
    display: block;
    text-decoration: none;
  }

  li + li {
    margin-top: 16px;
  }
}
</style>

// angular/src/app/components/list-repositories/list-repositories.component.ts
import { Component, Input, OnInit } from '@angular/core';
import {IRepository} from '../../services/repository/repository.service';

@Component({
  selector: 'app-list-repositories',
  templateUrl: './list-repositories.component.html',
  styleUrls: ['./list-repositories.component.scss']
})
export class ListRepositoriesComponent implements OnInit {
  @Input() repositories: IRepository[];
  constructor() { }

  ngOnInit(): void {
  }

}

<ul class="list">
  <li *ngFor="let repository of repositories">
    <a [routerLink]="['/repositorios', repository.owner.login, repository.name]" >
      <app-bar-info
        [title]="repository.full_name"
        [description]="repository.description"
        [avatar]="repository.owner.avatar_url"
        [alt]="repository.owner.login"
      >
      </app-bar-info>
    </a>
  </li>
</ul>
