// vue/src/components/header.vue
<template>
  <header>
    <img src="@/assets/logo.svg" alt="Github Explorer" />

    <router-link v-if="showButtonBack" tag="a" to="/">
      <img src="@/assets/icons/FiChevronLeft.svg" alt="fi chevron left" />
      Voltar
    </router-link>
  </header>
</template>

<script>
export default {
  props: {
    showButtonBack: {
      type: Boolean,
      default: () => false,
    },
  },
  name: "Header",
};
</script>

<style lang="scss" scoped>
header {
  align-items: center;
  display: flex;
  justify-content: space-between;

  a {
    align-items: center;
    color: #a8a8b3;
    display: flex;
    text-decoration: none;
    transition: 0.2s ease-in-out color;

    &:hover {
      color: #666;
    }

    img {
      margin-right: 4px;
    }
  }
}
</style>

// angular/src/app/components/header/header.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  @Input() showButtonBack: boolean
  constructor() { }

  ngOnInit(): void {
  }

}

<header>
  <img src="/assets/logo.svg" alt="Github Explorer" />

  <a *ngIf="showButtonBack" [routerLink]="['/']" routerLinkActive="router-link-active">
    <img src="/assets/icons/FiChevronLeft.svg.svg" alt="voltar" />
    Voltar
  </a>
</header>
