// vue/src/components/list-issues.vue
<template>
  <ul class="list">
    <li v-for="issue in issuesInternal" :key="issue.full_name">
      <a :href="issue.html_url">
        <bar-info :title="issue.title" :description="issue.user.login" />
      </a>
    </li>
  </ul>
</template>

<script>
import BarInfo from "@/components/bar-info.vue";
export default {
  name: "ListIssue",
  components: {
    BarInfo,
  },
  props: {
    link: Boolean,
    issues: {
      type: Array,
      require: true,
    },
  },
  data() {
    return {
      issuesInternal: [],
    };
  },
  watch: {
    issues(newValue) {
      return (this.issuesInternal = newValue);
    },
  },
  mounted() {
    this.issuesInternal = this.issues;
  },
};
</script>

// angular/src/app/components/lists/list-issues/list-issues.component.ts
import { Component, Input, OnInit } from '@angular/core';
import {Issue} from '../../../services/repository/repository.service';

@Component({
  selector: 'app-list-issues',
  templateUrl: './list-issues.component.html',
  styleUrls: ['./list-issues.component.scss']
})
export class ListIssuesComponent implements OnInit {
  @Input() issues: Issue[]
  constructor() { }

  ngOnInit(): void {
  }

}


  <ul class="list">
    <li *ngFor="let issue of issues">
      <a [href]="issue.html_url">
        <app-bar-info [title]="issue.title" [description]="issue.user.login"></app-bar-info>
      </a>
    </li>
  </ul>
