// react/src/components/bar-info/index.tsx
/* eslint-disable react/jsx-indent */
/* eslint-disable react/prop-types */
import React from 'react';
import { FiChevronRight } from 'react-icons/fi';
import { Bar } from './style';

type BarInfoProps = {
  title: string;
  description: string;
  avatar?: string;
  alt?: string;
};

const BarInfo: React.FC<BarInfoProps> = ({
  title,
  description,
  alt,
  avatar,
}) => (
  <Bar>
    <article>
      {avatar && <img src={avatar} alt={alt} />}
      <div>
        <strong>{title}</strong>
        <p>{description}</p>
      </div>
      <FiChevronRight size={20} />
    </article>
  </Bar>
);

export default BarInfo;

// angular/src/app/components/bar-info/bar-info.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-bar-info',
  templateUrl: './bar-info.component.html',
  styleUrls: ['./bar-info.component.scss']
})
export class BarInfoComponent implements OnInit {
  @Input() alt: string;
  @Input() avatar: string;
  @Input() description: string;
  @Input() title: string;

  constructor() { }

  ngOnInit(): void {
  }

}

<article class="bar-info">
  <img *ngIf="avatar" [src]="avatar" [alt]="alt" />
  <div>
    <strong>{{ title }}</strong>
    <p>{{ description }}</p>
  </div>
  <img
    class="arrow"
    src="/assets/icons/FiChevronRight.svg"
    alt="Chevron Right"
  />
</article>
