// angular/src/app/pages/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { IRepository, RepositoryService } from 'src/app/services/repository/repository.service';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {
  repositories: IRepository[]

  constructor(private repositoryService: RepositoryService) {
  }

  ngOnInit(): void {
    this.repositories = this.repositoryService.getLocalRepository();
  }

  getRepository(repository: string){
    if(typeof repository !== "string") return;

    this.repositoryService.getRepositoryData(repository).subscribe((reponse) => {
      const repositories = [...this.repositories, reponse];
      this.repositoryService.setRepository(repositories);
      this.repositories = repositories
    })
  }
}

<div class="Dashboard">
  <img src="/assets/logo.svg" alt="Github Explorer" />
  <h2 class="title">Explore repositórios no Github.</h2>
  <app-form-repository (submit)="getRepository($event)"></app-form-repository>
  <app-list-repositories [repositories]="repositories"></app-list-repositories>
</div>

// vue/src/views/Dashboard.vue
<template>
  <div class="Dashboard">
    <img src="@/assets/logo.svg" alt="Github Explorer" />
    <h2 class="title">Explore repositórios no Github.</h2>
    <form-repository @submit="getRepository" />
    <list-repositories :repositories="repositories" />
  </div>
</template>

<script>
import ListRepositories from "@/components/list-repositories.vue";
import FormRepository from "@/components/form-repository.vue";
import RepositoryService from "@/services/repository.js";

export default {
  name: "Dashboard",
  components: {
    FormRepository,
    ListRepositories,
  },
  data() {
    return {
      repositories: [],
    };
  },
  methods: {
    async getRepository(repository) {
      const repositories = await RepositoryService.getRepositoryData(
        repository
      );
      this.setRepositories([repositories.data]);
    },
    setRepositories(newRepository) {
      const repositories = [...this.repositories, ...newRepository];
      RepositoryService.setRepository(repositories);
      this.repositories = repositories;
    },
  },
  mounted() {
    this.repositories = RepositoryService.getLocalRepository();
  },
};
</script>

<style lang="scss">
.title {
  color: #3a3a3a;
  font-size: 48px;
  margin-top: 80px;
  max-width: 450px;
}
</style>
