// src/pages/Dashboard/index.tsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Title, Repositories } from './styles';
import logo from '../../assets/logo.svg';
import BarInfo from '../../components/bar-info/index';
import Form from '../../components/form/index';
import RepositoryService, { IRepository } from '../../services/repository';

const Dashboard: React.FC = () => {
  const [repositories, setRepositories] = useState<IRepository[]>(() =>
    RepositoryService.getLocalRepository(),
  );

  useEffect(() => {
    RepositoryService.setRepository(repositories);
  }, [repositories]);

  function handleAddRepository(newRepo: string): void {
    RepositoryService.getRepositoryData(newRepo).then(({ data }) =>
      setRepositories([...repositories, data]),
    );
  }

  return (
    <>
      <img src={logo} alt="Github Explorer" />
      <Title>Explore repositórios no Github.</Title>
      <Form submit={(newRepo: string) => handleAddRepository(newRepo)} />
      <Repositories>
        {repositories.map(repository => (
          <Link
            key={repository.full_name}
            to={`/repositorios/${repository.full_name}`}
          >
            <BarInfo
              title={repository.full_name}
              description={repository.description}
              avatar={repository.owner.avatar_url}
              alt={repository.owner.login}
            />
          </Link>
        ))}
      </Repositories>
    </>
  );
};

export default Dashboard;

// vue/src/views/Dashboard.vue
<template>
  <div class="Dashboard">
    <img src="@/assets/logo.svg" alt="Github Explorer" />
    <h2 class="title">Explore repositórios no Github.</h2>
    <form-repository @submit="getRepository" />
    <list-repositories :repositories="repositories" />
  </div>
</template>

<script>
import ListRepositories from "@/components/list-repositories.vue";
import FormRepository from "@/components/form-repository.vue";
import RepositoryService from "@/services/repository.js";

export default {
  name: "Dashboard",
  components: {
    FormRepository,
    ListRepositories,
  },
  data() {
    return {
      repositories: [],
    };
  },
  methods: {
    async getRepository(repository) {
      const repositories = await RepositoryService.getRepositoryData(
        repository
      );
      this.setRepositories([repositories.data]);
    },
    setRepositories(newRepository) {
      const repositories = [...this.repositories, ...newRepository];
      RepositoryService.setRepository(repositories);
      this.repositories = repositories;
    },
  },
  mounted() {
    this.repositories = RepositoryService.getLocalRepository();
  },
};
</script>

<style lang="scss">
.title {
  color: #3a3a3a;
  font-size: 48px;
  margin-top: 80px;
  max-width: 450px;
}
</style>
