// angular/src/app/pages/repository/repository.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { IRepository, Issue, RepositoryService } from 'src/app/services/repository/repository.service';

@Component({
  selector: 'app-repository',
  templateUrl: './repository.component.html',
  styleUrls: ['./repository.component.scss']
})
export class RepositoryComponent implements OnInit {
  repository: IRepository;
  issues: Issue[];
  constructor(private repositoryService:RepositoryService, private route: ActivatedRoute) { }

  ngOnInit(): void {
    this.route.params.subscribe((params) => {
      const repository = `${params.owner}/${params.repository}`

      this.repositoryService.getRepositoryData(repository).subscribe(repositories => {
        this.repository = repositories;
      })

      this.repositoryService.getIssue(repository).subscribe(issues => {
        this.issues = issues;
      })
    });
  }
}

<div class="about">
  <app-header [showButtonBack]="true"></app-header>
  <app-repository-info [repository]="repository"></app-repository-info>
  <app-list-issues [issues]="issues"></app-list-issues>
</div>

// vue/src/views/Repository.vue
<template>
  <div class="about">
    <global-header :showButtonBack="true" />

    <main>
      <repository-info :repository="repository" />
      <list-issues :link="true" :issues="issue" />
    </main>
  </div>
</template>

<script>
import GlobalHeader from "@/components/header.vue";
import RepositoryInfo from "@/components/repository-info";
import ListIssues from "@/components/list-issues.vue";
import RepositoryService from "@/services/repository.js";

export default {
  name: "Repository",
  components: { RepositoryInfo, ListIssues, GlobalHeader },
  data() {
    return {
      issue: [],
      repository: {},
    };
  },
  mounted() {
    const repository = `${this.$route.params.owner}/${this.$route.params.repository}`;

    RepositoryService.getRepositoryData(repository).then(({ data }) => {
      this.repository = data;
    });

    RepositoryService.getIssue(repository).then(({ data }) => {
      this.issue = data;
    });
  },
};
</script>
